AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API

Resources:
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-java/target/lambda-java-1.0-SNAPSHOT.jar
      Handler: com.filichkin.blog.lambda.v2.handler.BookHandler::handleRequest
      Runtime: java11
      MemorySize: 256
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 15
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /java/book
            Method: post

  GraalVMLatestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: graalvm_latest/dist/function.zip
      MemorySize: 128
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 10

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /graal-17/book
            Method: post

  GraalVM11Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: graalvm_11-21.3/dist/function.zip
      MemorySize: 128
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 10

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /graal-11/book
            Method: post

  QuarkusVMFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: quarkus-aws-lambda/target/function.zip
      MemorySize: 256
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 10
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /quarkus/book
            Method: post

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: APIExport
